// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCfhxv4u2VJXhqvyVMCUcpFu-0V5LYFSE',
    appId: '1:16011012360:web:590b401108af2cb2b564bd',
    messagingSenderId: '16011012360',
    projectId: 'dassi-2a557',
    authDomain: 'dassi-2a557.firebaseapp.com',
    storageBucket: 'dassi-2a557.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHikMidyKA0f0HnLmQprxlRsKwopNHB3s',
    appId: '1:16011012360:android:dd76f3a3900754dab564bd',
    messagingSenderId: '16011012360',
    projectId: 'dassi-2a557',
    storageBucket: 'dassi-2a557.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9dUOr1OxJ3EpJJDFPi6k9ecFIpEVySWk',
    appId: '1:16011012360:ios:f68d74800b4a58fdb564bd',
    messagingSenderId: '16011012360',
    projectId: 'dassi-2a557',
    storageBucket: 'dassi-2a557.appspot.com',
    iosBundleId: 'com.example.dassi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9dUOr1OxJ3EpJJDFPi6k9ecFIpEVySWk',
    appId: '1:16011012360:ios:f68d74800b4a58fdb564bd',
    messagingSenderId: '16011012360',
    projectId: 'dassi-2a557',
    storageBucket: 'dassi-2a557.appspot.com',
    iosBundleId: 'com.example.dassi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBCfhxv4u2VJXhqvyVMCUcpFu-0V5LYFSE',
    appId: '1:16011012360:web:81328017c75a4f22b564bd',
    messagingSenderId: '16011012360',
    projectId: 'dassi-2a557',
    authDomain: 'dassi-2a557.firebaseapp.com',
    storageBucket: 'dassi-2a557.appspot.com',
  );
}
