import 'package:country_picker/country_picker.dart';

final List<Country> francophoneCountries = [
  Country(
    phoneCode: '241',
    countryCode: 'GA',
    e164Sc: 241,
    geographic: true,
    level: 1,
    name: 'Gabon',
    example: 'Gabon',
    displayName: 'Gabon',
    displayNameNoCountryCode: 'GA',
    e164Key: '',
  ),
  Country(
    phoneCode: '213',
    countryCode: 'DZ',
    e164Sc: 213,
    geographic: true,
    level: 1,
    name: 'Algérie',
    example: 'Algérie',
    displayName: 'Algérie',
    displayNameNoCountryCode: 'DZ',
    e164Key: '',
  ),
  Country(
    phoneCode: '32',
    countryCode: 'BE',
    e164Sc: 32,
    geographic: true,
    level: 1,
    name: 'Belgique',
    example: 'Belgique',
    displayName: 'Belgique',
    displayNameNoCountryCode: 'BE',
    e164Key: '',
  ),
  Country(
    phoneCode: '229',
    countryCode: 'BJ',
    e164Sc: 229,
    geographic: true,
    level: 1,
    name: 'Bénin',
    example: 'Bénin',
    displayName: 'Bénin',
    displayNameNoCountryCode: 'BJ',
    e164Key: '',
  ),
  Country(
    phoneCode: '226',
    countryCode: 'BF',
    e164Sc: 226,
    geographic: true,
    level: 1,
    name: 'Burkina Faso',
    example: 'Burkina Faso',
    displayName: 'Burkina Faso',
    displayNameNoCountryCode: 'BF',
    e164Key: '',
  ),
  Country(
    phoneCode: '237',
    countryCode: 'CM',
    e164Sc: 237,
    geographic: true,
    level: 1,
    name: 'Cameroun',
    example: 'Cameroun',
    displayName: 'Cameroun',
    displayNameNoCountryCode: 'CM',
    e164Key: '',
  ),
  Country(
    phoneCode: '242',
    countryCode: 'CG',
    e164Sc: 242,
    geographic: true,
    level: 1,
    name: 'République du Congo',
    example: 'République du Congo',
    displayName: 'République du Congo',
    displayNameNoCountryCode: 'CG',
    e164Key: '',
  ),
  Country(
    phoneCode: '243',
    countryCode: 'CD',
    e164Sc: 243,
    geographic: true,
    level: 1,
    name: 'République démocratique du Congo',
    example: 'République démocratique du Congo',
    displayName: 'République démocratique du Congo',
    displayNameNoCountryCode: 'CD',
    e164Key: '',
  ),
  Country(
    phoneCode: '225',
    countryCode: 'CI',
    e164Sc: 225,
    geographic: true,
    level: 1,
    name: 'Côte d`\'Ivoire',
    example: 'Côte d`\'Ivoire',
    displayName: 'Côte d`\'Ivoire',
    displayNameNoCountryCode: 'CI',
    e164Key: '',
  ),
  Country(
    phoneCode: '20',
    countryCode: 'EG',
    e164Sc: 20,
    geographic: true,
    level: 1,
    name: 'Egypte',
    example: 'Egypte',
    displayName: 'Egypte',
    displayNameNoCountryCode: 'EG',
    e164Key: '',
  ),
  Country(
    phoneCode: '33',
    countryCode: 'FR',
    e164Sc: 33,
    geographic: true,
    level: 1,
    name: 'France',
    example: 'France',
    displayName: 'France',
    displayNameNoCountryCode: 'FR',
    e164Key: '',
  ),
  Country(
    phoneCode: '224',
    countryCode: 'GN',
    e164Sc: 224,
    geographic: true,
    level: 1,
    name: 'Guinée Conakry',
    example: 'Guinée Conakry',
    displayName: 'Guinée Conakry',
    displayNameNoCountryCode: 'GN',
    e164Key: '',
  ),
  // Ajoutez d'autres pays francophones ici
];