// Liste des pays francophones d'Afrique
const List<String> francophoneAfricanCountries = [
  'Algérie',
  'Bénin',
  'Burkina Faso',
  'Burundi',
  'Cameroun',
  'Comores',
  'Congo',
  'Côte d\'Ivoire',
  'Djibouti',
  'Égypte',
  'Gabon',
  'Guinée',
  'Guinée-Bissau',
  'Guinée équatoriale',
  'Madagascar',
  'Mali',
  'Maroc',
  'Maurice',
  'Mauritanie',
  'Niger',
  'République centrafricaine',
  'RDC',
  'Rwanda',
  'Sénégal',
  'Seychelles',
  'Tchad',
  'Togo',
  'Tunisie',
];